### ISSUE TITLE
Advert's category always default to toys?

### ISSUE THREAD

**Issue by chewlim** [marketplacer/api.marketplacer.com#33]
After uploading a product, the category is incorrect. SKU: CS9013TO2_Ebony (advert id 100496160). Product category chosen as "convertible-car-seats", but it appears to be "toy" in Tinitrader.

Any idea?

**Comment by robotdana** [comment]
That is strange. 

How are you assigning the taxon? with `map_taxon` or with `taxon_slug`?

**Comment by chewlim** [comment]
we use taxon_slug

**Comment by robotdana** [comment]
I'm just looking at the logs,
It looks like the advert received args correctly in a way I'd think would work.
Then the advert was updated in the UI to have the toys taxon (possibly inadvertently, we might have a bug in our UI code)

Is it possible for you to create a new (unpublished) copy of this advert and let me know its ID without looking at the Advert edit UI? That way I can check in the database and confirm it could be a bug with the UI rather than the API.

Thanks

**Comment by chewlim** [comment]
Do you want me to submit it via API or directly via the UI?

**Comment by robotdana** [comment]
Submit via the api please

**Comment by chewlim** [comment]
See Advert Id 100496164.

Submitted with "baby-carriers"

**Comment by robotdana** [comment]
It looks like you're setting the `map_taxon`attribute to an empty string. We weren't expecting people to do that and it's breaking (I've added it to our bug tracker now). To work around it for now, Remove any mention of that attribute entirely, and things will be assigned to the right category. (also remove `map_brand` because you're using `brand_slug`, and this may also have unforseen issues).

e.g. This will create the wrong taxon:
```
{
    "data": {
        "type": "adverts",
        "attributes": {
            "brand_slug": "mamaway",
            "description": "The description",
            "map_brand": "Mamaway",
            "map_taxon": "",
            "price": 100.00,
            "taxon_slug": "baby-carriers",
            "title": "The title"
        }
    }
}
```
This creates the right one:
```
{
    "data": {
        "type": "adverts",
        "attributes": {
            "brand_slug": "mamaway",
            "description": "The description",
            "price": 100.00,
            "taxon_slug": "baby-carriers",
            "title": "The title"
        }
    }
}
```

**Comment by robotdana** [comment]
Thanks for this. I ended up fixing this bug here if you're interested: https://github.com/ClosureTree/closure_tree/pull/288
